name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          fetchViaCommits: true
          fetchReviewers: true

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.build-changelog.outputs.changelog}}

        #   runs-on: ubuntu-latest
        #   steps:
        #     - uses: actions/checkout@v4
        #     - uses: actions/setup-node@v3
        #       with:
        #         node-version: '20.x'
        #         registry-url: 'https://registry.npmjs.org'
        #     - run: yarn
        #     - run: yarn build
        #     - run: yarn publish
        #       env:
        #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
